apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: my-hello-world-app-functional-test
  namespace: argocd
spec:
    destination:
        server: https://kubernetes.default.svc
        namespace: multiapp-functional-test
    project: default
    source:
        path: dev-tmp
        repoURL: https://github.com/borikoss/charts-repo-actions-demo-gitops
        targetRevision: main
        directory:
            recurse: true
            include: '*.yaml'
    syncPolicy:
        automated:
            prune: true
            selfHeal: true
            allowEmpty: false
        syncOptions:
        # namespace creation set false to enable a namespace manifest declaration
        - CreateNamespace=false